- 👋 TIGO MONEY, I’m @Bloqueado
- 👀 SE INICIO PARA VERIFICAR I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
Bloqueado/Bloqueado is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--- tu cuenta a sido bloqueado debe dar inicio
